In [7]:
import numpy as np
#length 10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
#3x5 float filled with 1
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
#3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# array with linear sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# array with five values evenly spaced
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# array 3x3 uniformly distributed with random values
np.random.random((3,3))

array([[0.69026219, 0.72955254, 0.73839427],
       [0.70409022, 0.15717632, 0.07166961],
       [0.52067789, 0.31429036, 0.97151447]])

In [13]:
#3x3 normally distributed random values with mean 0 and sd 1
np.random.normal(0,1,(3,3))

array([[-0.87233021,  0.26997288, -1.65532173],
       [-0.00339628,  0.36604127,  0.52240517],
       [-0.23549049,  0.00352443,  0.11398539]])

In [14]:
#create 3x3 array random ints interval [0,10)
np.random.randint(0,10,(3,3))

array([[7, 1, 4],
       [3, 2, 0],
       [2, 5, 1]])

In [15]:
#3x3 id matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#uninitiated array 3 ints
np.empty(3)

array([1., 1., 1.])